version: "3.2"

services:

  frontend-reviews:
    container_name: frontend-reviews
    image: 'chaphe/frontend-reviews-image:1.0'
    environment:
      - REVIEWS_URL=http://localhost:3000
    ports:
      - "81:80"
    networks:
      - book-store-network

  # CATALOG

  frontend-catalog:
    container_name: frontend-catalog
    image: 'chaphe/frontend-catalog-image:1.0'
    ports:
      - "82:80"
    networks:
      - book-store-network

  # STORE

  frontend-store:
    container_name: frontend-store
    image: 'chaphe/frontend-store-image:1.0'
    environment:
      - STORE_URL=http://137.184.238.11:8082
      - REVIEWS_URL=http://137.184.238.11:3000
      - CATALOG_URL=http://137.184.238.11:8081
    ports:
      - "80:80"
    networks:
      - book-store-network

      
networks:
  book-store-network:
    driver: bridge